export const GLOBAL_CITIES = [
  'Dubai', 'Bali', 'Paris', 'London', 'New York', 'Tokyo', 'Singapore', 'Bangkok',
  'Rome', 'Istanbul', 'Barcelona', 'Amsterdam', 'Kuala Lumpur', 'Seoul', 'Milan',
  'Prague', 'Vienna', 'Taipei', 'Los Angeles', 'Las Vegas', 'Madrid', 'Venice',
  'Dublin', 'Florence', 'Athens', 'Sydney', 'Melbourne', 'Hong Kong', 'Macau',
  'Toronto', 'Vancouver', 'San Francisco', 'Miami', 'Chicago', 'Washington D.C.',
  'Cancun', 'Punta Cana', 'Maldives', 'Mauritius', 'Seychelles', 'Phuket',
  'Pattaya', 'Chiang Mai', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Kyoto',
  'Osaka', 'Sapporo', 'Fukuoka', 'Taipei', 'Kaohsiung', 'Manila', 'Cebu',
  'Boracay', 'Jakarta', 'Yogyakarta', 'Lombok', 'Kuta', 'Ubud', 'Penang',
  'Langkawi', 'Johor Bahru', 'Malacca', 'Colombo', 'Kandy', 'Galle', 'Kathmandu',
  'Pokhara', 'Thimphu', 'Paro', 'Dhaka', 'Male', 'Dubai', 'Abu Dhabi', 'Sharjah',
  'Doha', 'Manama', 'Muscat', 'Salalah', 'Kuwait City', 'Riyadh', 'Jeddah',
  'Mecca', 'Medina', 'Amman', 'Petra', 'Aqaba', 'Beirut', 'Cairo', 'Alexandria',
  'Luxor', 'Sharm El-Sheikh', 'Hurghada', 'Marrakech', 'Casablanca', 'Fes',
  'Tangier', 'Tunis', 'Algiers', 'Cape Town', 'Johannesburg', 'Durban',
  'Pretoria', 'Nairobi', 'Mombasa', 'Zanzibar', 'Dar es Salaam', 'Kigali',
  'Addis Ababa', 'Accra', 'Lagos', 'Abuja', 'Dakar', 'Buenos Aires',
  'Rio de Janeiro', 'Sao Paulo', 'Santiago', 'Lima', 'Cusco', 'Machu Picchu',
  'Bogota', 'Cartagena', 'Medellin', 'Quito', 'Galapagos', 'Caracas',
  'Montevideo', 'La Paz', 'Asuncion', 'Panama City', 'San Jose', 'San Salvador',
  'Guatemala City', 'Antigua', 'Belize City', 'Havana', 'San Juan',
  'Santo Domingo', 'Punta Cana', 'Nassau', 'Kingston', 'Montego Bay',
  'Port of Spain', 'Bridgetown', 'Reykjavik', 'Oslo', 'Stockholm', 'Copenhagen',
  'Helsinki', 'Tallinn', 'Riga', 'Vilnius', 'Warsaw', 'Krakow', 'Budapest',
  'Prague', 'Bratislava', 'Bucharest', 'Sofia', 'Belgrade', 'Zagreb',
  'Dubrovnik', 'Split', 'Sarajevo', 'Ljubljana', 'Tirana', 'Skopje', 'Athens',
  'Santorini', 'Mykonos', 'Crete', 'Rhodes', 'Istanbul', 'Antalya', 'Cappadocia',
  'Bodrum', 'Izmir', 'Rome', 'Venice', 'Florence', 'Milan', 'Naples', 'Amalfi',
  'Sicily', 'Sardinia', 'Paris', 'Nice', 'Cannes', 'Lyon', 'Marseille',
  'Bordeaux', 'Madrid', 'Barcelona', 'Seville', 'Valencia', 'Granada',
  'Ibiza', 'Mallorca', 'Tenerife', 'Lisbon', 'Porto', 'Algarve', 'Faro',
  'London', 'Edinburgh', 'Glasgow', 'Manchester', 'Liverpool', 'Bath',
  'Belfast', 'Dublin', 'Galway', 'Cork', 'Amsterdam', 'Rotterdam', 'The Hague',
  'Brussels', 'Bruges', 'Antwerp', 'Berlin', 'Munich', 'Frankfurt', 'Hamburg',
  'Cologne', 'Zurich', 'Geneva', 'Lucerne', 'Interlaken', 'Vienna', 'Salzburg',
  'Innsbruck', 'Auckland', 'Wellington', 'Christchurch', 'Queenstown',
  'Fiji', 'Tahiti', 'Bora Bora', 'Honolulu', 'Maui', 'Kaua\'i',
  'Anchorage', 'Juneau', 'Banff', 'Jasper', 'Whistler', 'Montreal',
  'Quebec City', 'Ottawa', 'Halifax'
];
